CREATE SCHEMA IF NOT EXISTS scout;

DROP TABLE IF EXISTS CLUB CASCADE;
DROP TABLE IF EXISTS PHONES CASCADE;

CREATE TABLE CLUB
(
    Name_Club VARCHAR(25) NOT NULL,
    City      VARCHAR(25) NOT NULL,
    Street    VARCHAR(50) NOT NULL,
    Build     CHAR(7)     NOT NULL,
    PRIMARY KEY (Name_Club)
);

CREATE TABLE PHONES
(
    Telephone CHAR(13)    NOT NULL,
    Name_Club VARCHAR(25) NOT NULL,
    PRIMARY KEY (Telephone),
    FOREIGN KEY (Name_Club) REFERENCES CLUB (Name_Club) ON DELETE CASCADE ON UPDATE CASCADE
);

